/**
 * Calo Scan — pilot dataset (5 SKUs)
 *
 * Real products from Vedant's 65-SKU list. Nutrition and ingredient data
 * researched via independent web research per product, cross-checked
 * against official brand sites, GCC retailer listings, and Open Food Facts
 * (see sourceUrls + dataConfidence on each product). An earlier draft of
 * this file estimated 4 of the 5 products' data instead of actually
 * researching it — that was a mistake, caught and corrected before this
 * data started driving new features (see dataConfidence / notes below for
 * the honest state of each SKU, including the one ingredient list —
 * Barakat OJ — that's inferred from the brand's single-ingredient labeling
 * pattern rather than a directly-sourced ingredients panel).
 *
 * Picked to stress-test the design, not to show five easy wins:
 *   - a Market item with a flagged allergen (Barebells)
 *   - a non-Market "clearly poor" case (Pringles)
 *   - a "clearly excellent" case (Nada yoghurt)
 *   - a Market item that scores Poor — the radical-transparency moment (7Days)
 *   - a natural-sugar nuance case, same honesty as the dates example (Barakat)
 *
 * allergens = directly present per the ingredients list ("Contains X").
 * mayContainAllergens = cross-contact / "may contain" warning only, not an
 * actual ingredient — a real, separate category on food labels, and worth
 * distinguishing rather than flattening into one bucket (see profile.js).
 *
 * priceAED is Vedant's own estimate for the prototype, not a real Calo
 * Market price — flagged clearly wherever it's shown.
 */

const PRODUCTS = [
  {
    id: "barebells-peanut-caramel-bar-55g",
    barcode: "7340001806618",
    name: "Salted Peanut Caramel Protein Bar",
    brand: "Barebells",
    category: "snacks",
    servingLabel: "55g (1 bar)",
    servingSizeG: 55,
    isCaloMarket: true,
    priceAED: 12,
    image: "assets/pilot/barebells-peanut-caramel-bar-55g.png",
    nutrition: { calories: 217, sugar_g: 2.1, satFat_g: 4.6, sodium_mg: 208, fiber_g: 6, protein_g: 16 },
    allergens: ["dairy", "soy", "peanut"],
    mayContainAllergens: ["wheat", "eggs", "tree_nuts", "sesame"],
    concernMarkers: [
      "Contains sugar alcohols (maltitol, xylitol) — can cause digestive discomfort in sensitive people",
      "Contains an artificial sweetener (sucralose)",
      "May contain traces of egg, tree nuts, sesame and wheat (cross-contact)",
    ],
    positiveFlags: ["16g protein per bar", "Low sugar for a candy-shaped bar (2.1g)", "6g fiber per bar"],
    verdict:
      "High protein and fiber for a treat-shaped bar — but relies on sugar alcohols and an artificial sweetener, not naturally low sugar.",
    ingredients: [
      { name: "Milk Proteins", flag: null, reason: "" },
      { name: "Maltitol", flag: "caution", reason: "Sugar alcohol (sweetener) — can cause digestive discomfort such as bloating, gas, or a laxative effect in some people when eaten in quantity." },
      { name: "Xylitol", flag: "caution", reason: "Sugar alcohol (sweetener) — generally well tolerated, but can cause digestive upset in large amounts. (Unrelated note: highly toxic to dogs if ingested.)" },
      { name: "Sucralose", flag: "caution", reason: "Artificial sweetener — approved as safe by the FDA and EFSA, but some consumers prefer to limit intake." },
      { name: "Peanuts", flag: "concern", reason: "Major allergen — can trigger severe, potentially life-threatening reactions in people with a peanut allergy." },
      { name: "Polydextrose", flag: "caution", reason: "Synthetic soluble fiber used as a bulking agent — generally recognized as safe, but can cause gas or bloating in sensitive individuals at higher intakes." },
      { name: "Hydrolyzed Collagen", flag: "caution", reason: "Protein sourced from cattle — not suitable for vegetarians or vegans; otherwise a well-established protein ingredient." },
      { name: "Glycerol", flag: "caution", reason: "Humectant that retains moisture — generally recognized as safe; large amounts have occasionally been linked to mild digestive upset." },
      { name: "Cocoa Butter", flag: null, reason: "" },
      { name: "Whole Milk Powder", flag: null, reason: "" },
      { name: "Cocoa Mass", flag: null, reason: "" },
      { name: "Soy Oil", flag: "caution", reason: "Highly refined — typically negligible soy protein, but still legally declared for people with severe soy allergy." },
      { name: "Salt", flag: null, reason: "" },
      { name: "Flavourings", flag: "caution", reason: "Generic label term covering natural and/or artificial flavour compounds; exact composition isn't disclosed." },
      { name: "Soy Lecithin", flag: "caution", reason: "Soy-derived emulsifier — typically only trace soy protein, but relevant for severe soy allergy." },
    ],
    dataConfidence: "high",
    sourceUrls: [
      "https://barebells.com/product/peanut-caramel/",
      "https://proteinpackage.co.uk/products/barebells-soft-protein-bar-salted-peanut-caramel",
      "https://world.openfoodfacts.org/product/7340001806618/salted-peanut-caramel-soft-protein-bar-barebells",
    ],
    dataNotes:
      "EU/UK formulation (barcode prefix 734 = Sweden) confirmed via barebells.com and an independent UK retailer, which match exactly. The US-market version sold via GNC/Amazon has a different recipe and barcode — not used here.",
  },
  {
    id: "pringles-original-200g",
    barcode: "5053990138722",
    name: "Original Potato Chips",
    brand: "Pringles",
    category: "snacks",
    servingLabel: "~30g (about 15 chips)",
    servingSizeG: 30,
    isCaloMarket: false,
    priceAED: 14,
    image: "assets/pilot/pringles-original-200g.png",
    nutrition: { calories: 158, sugar_g: 0.3, satFat_g: 0.9, sodium_mg: 120, fiber_g: 1.2, protein_g: 1.9 },
    allergens: ["wheat"],
    mayContainAllergens: ["dairy", "soy"],
    concernMarkers: [
      "Reconstituted potato, not whole potato slices, fried in vegetable oil",
      "Contains emulsifier E471",
      "May contain milk and soy (cross-contact)",
      "Energy-dense — easy to eat several servings in one sitting",
    ],
    positiveFlags: ["No added sugar"],
    verdict:
      "Reconstituted potato fried in oil with an emulsifier — light on sugar, but calorie- and sodium-dense per 100g.",
    ingredients: [
      { name: "Dehydrated Potatoes", flag: null, reason: "" },
      { name: "Sunflower Oil", flag: null, reason: "" },
      { name: "Corn Flour", flag: null, reason: "" },
      { name: "Wheat Flour", flag: null, reason: "Contains gluten — declared allergen, not a health concern on its own." },
      { name: "Rice Flour", flag: null, reason: "" },
      { name: "Maltodextrin", flag: "caution", reason: "Highly refined starch-derived filler — digests quickly and can spike blood sugar despite being technically a \"starch,\" not a sugar." },
      { name: "Emulsifier (E471)", flag: "caution", reason: "Mono- and diglycerides of fatty acids — a permitted, common emulsifier; flagged for visibility since some consumers prefer to avoid additives generally." },
      { name: "Rapeseed Oil", flag: null, reason: "" },
      { name: "Salt", flag: null, reason: "" },
      { name: "Colour (Annatto Norbixin)", flag: null, reason: "Natural plant-derived colorant — very rare sensitivity reports, generally considered safe." },
    ],
    dataConfidence: "high",
    sourceUrls: [
      "https://www.pringles.com/ie/products/flavours/pringles-original-200g.html",
      "https://www.ocado.com/products/pringles-original-crisps-can/58593011",
      "https://world.openfoodfacts.org/product/5053990138722/pringles-original",
    ],
    dataNotes:
      "This is the European/GCC-distribution formulation (matches this exact barcode) — the US 5.2oz Kellogg's SKU has a different recipe under a different barcode and was excluded.",
  },
  {
    id: "nada-zero-fat-greek-yoghurt-160g",
    barcode: "6281018131786",
    name: "Zero Fat Greek Yoghurt (16g Protein)",
    brand: "Nada",
    category: "other_dairy_products",
    servingLabel: "160g (1 pack)",
    servingSizeG: 160,
    isCaloMarket: true,
    priceAED: 6.5,
    image: "assets/pilot/nada-zero-fat-greek-yoghurt-160g.jpg",
    nutrition: { calories: 101, sugar_g: 8, satFat_g: 0.3, sodium_mg: 69, fiber_g: 0, protein_g: 16 },
    allergens: ["dairy"],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: [
      "16g protein per pack",
      "Zero fat",
      "No added sugar — what's here is naturally occurring milk lactose",
      "Live yoghurt culture",
    ],
    verdict:
      "Fat-free, 16g protein, nothing added — about as close to a default-good dairy choice as it gets.",
    ingredients: [
      { name: "Fresh Cow's Non-Fat Milk", flag: null, reason: "" },
      { name: "Milk Protein", flag: null, reason: "Added to boost protein content and firm the texture — a standard dairy ingredient, not an additive of concern." },
      { name: "Yoghurt Culture", flag: null, reason: "Live bacterial culture used for fermentation — standard and expected in yoghurt." },
      { name: "Vitamin A", flag: null, reason: "Added nutrient (fortification)." },
      { name: "Vitamin D", flag: null, reason: "Added nutrient (fortification)." },
    ],
    dataConfidence: "high",
    sourceUrls: [
      "https://nada.com.sa/en/product/greek-yoghurt-0-fat-plain/",
      "https://ae.openfoodfacts.org/mountaj/6281018131786/greek-yogurt-nada",
      "https://www.sharjahcoop.ae/en/nada-greek-yoghurt-plain-zero-fat-160g/p/6281018131786",
    ],
    dataNotes:
      "Genuinely clean ingredient list — no thickeners, stabilizers, preservatives or sweeteners. Nothing was flagged because nothing here warrants it, not because the list was shortened.",
  },
  {
    id: "7days-chocolate-croissant-6x55g",
    barcode: "6281183000061",
    name: "Chocolate Croissant",
    brand: "7Days",
    category: "longer_life_bakery",
    servingLabel: "55g (1 croissant)",
    servingSizeG: 55,
    isCaloMarket: false,
    priceAED: 11,
    image: "assets/pilot/7days-chocolate-croissant-6x55g.png",
    nutrition: { calories: 257, sugar_g: 8, satFat_g: 8, sodium_mg: 72, fiber_g: 1, protein_g: 4 },
    allergens: ["wheat", "dairy", "soy"],
    mayContainAllergens: [],
    concernMarkers: [
      "Palm oil is a primary ingredient, in both the dough and the filling",
      "Saturated fat is high for the size — about 40% of a full day's recommended limit in one piece",
      "Several synthetic preservatives and emulsifiers (calcium propionate, potassium sorbate, polyglycerol esters)",
      "Contains BHA (E320), a preservative facing extra regulatory scrutiny in several countries",
    ],
    positiveFlags: ["Individually wrapped 55g portion supports portion control"],
    verdict:
      "High in saturated fat and sugar for its size, with several processing markers — a treat, not a daily habit.",
    ingredients: [
      { name: "Wheat Flour", flag: null, reason: "" },
      { name: "Palm Oil", flag: "caution", reason: "Appears in both the dough and the chocolate filling — high in saturated fat, and the main driver of this product's 8g saturated fat per serving." },
      { name: "Sugar", flag: "caution", reason: "Appears in both the dough and the filling — the main driver of this product's 8g sugar per serving." },
      { name: "Glucose-Fructose Syrup", flag: "caution", reason: "A refined added-sugar syrup (similar to high-fructose corn syrup), used in both dough and filling to sweeten and retain moisture." },
      { name: "Cocoa Powder", flag: null, reason: "" },
      { name: "Milk Solids", flag: null, reason: "" },
      { name: "Sorbitol (E420)", flag: "caution", reason: "Sugar-alcohol humectant — can have a mild laxative effect in large cumulative amounts, though the amount in one croissant is small." },
      { name: "Propylene Glycol (E1520)", flag: "caution", reason: "Humectant that retains moisture in the filling — approved as safe at permitted food-use levels." },
      { name: "Polyglycerol Esters of Fatty Acids (E475)", flag: "caution", reason: "Emulsifier that blends fat and sugar in the filling — permitted, flagged here for additive-conscious visibility." },
      { name: "Potassium Sorbate (E202)", flag: "caution", reason: "Common mold-inhibiting preservative, used in both dough and filling — well studied and permitted." },
      { name: "Artificial Vanilla Flavour", flag: "caution", reason: "Synthetic flavouring in place of real vanilla, used in both dough and filling — approved as safe, some consumers prefer to avoid artificial flavourings." },
      { name: "BHA — Butylated Hydroxyanisole (E320)", flag: "concern", reason: "Synthetic antioxidant preservative that has drawn extra regulatory scrutiny (e.g. California Prop 65 listing, ongoing EU re-evaluation) and is restricted in some product categories in several countries — one of the more commonly flagged food additives." },
      { name: "Citric Acid (E330)", flag: null, reason: "Common, well-tolerated acidity regulator." },
      { name: "Mono- and Diglycerides of Fatty Acids (E471)", flag: "caution", reason: "Dough emulsifier improving softness and shelf life — specified here as vegetable-derived." },
      { name: "Soya Lecithin", flag: null, reason: "Emulsifier — declared allergen source, otherwise unremarkable." },
      { name: "Wheat Gluten", flag: null, reason: "" },
      { name: "Yeast", flag: null, reason: "" },
      { name: "Calcium Propionate (E282)", flag: "caution", reason: "Mold-inhibiting preservative common in packaged bread and pastry — permitted and well studied." },
      { name: "Nature-Identical Butter Flavour", flag: "caution", reason: "Chemically synthesized to replicate a real-butter taste rather than using actual butter — approved as safe." },
      { name: "Whey Powder", flag: null, reason: "" },
      { name: "Xanthan Gum (E415)", flag: null, reason: "Common, well-tolerated stabilizer." },
      { name: "Ascorbic Acid / Vitamin C (E300)", flag: null, reason: "Flour treatment agent, also a vitamin — not a concern." },
      { name: "Wheat Starch", flag: null, reason: "" },
    ],
    dataConfidence: "medium",
    sourceUrls: [
      "https://www.almarai.com/en/brands/seven-days/bakery/croissant/chocolate-croissant",
      "https://world.openfoodfacts.org/product/6281183000023/7days-croissant",
      "https://uae.ahmarket.com/en/7d-croissant-chocl-b5g1f-330g_6281183000061.html",
    ],
    dataNotes:
      "Nutrition figures are high-confidence (Almarai's own brand page, exact 55g size match). The verbatim ingredients list came from an Open Food Facts entry for the same product at a closely-related barcode — Almarai's own page didn't expose ingredient text. One retailer showed a differently-worded snippet that didn't fully reconcile, hence medium (not high) confidence on exact ingredient wording/order specifically.",
  },
  {
    id: "barakat-fresh-orange-juice-1l",
    barcode: "6291100931514",
    name: "Fresh Orange Juice",
    brand: "Barakat",
    category: "beverages",
    servingLabel: "250ml",
    servingSizeG: 250,
    isCaloMarket: true,
    priceAED: 15,
    image: "assets/pilot/barakat-fresh-orange-juice-1l.jpg",
    nutrition: { calories: 88, sugar_g: 20, satFat_g: 0, sodium_mg: 0, fiber_g: 2.5, protein_g: 2.5 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["100% fruit, no added sugar, no preservatives", "Source of vitamin C"],
    verdict:
      "100% fresh-squeezed, nothing added — but naturally sweet: 20g sugar per glass still counts toward your budget.",
    ingredients: [
      { name: "Orange Juice (100%, freshly squeezed)", flag: null, reason: "" },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://barakatfresh.ae/orange-juice-1l.html", "https://www.talabat.com/uae/talabat-mart/product/barakat-fresh-orange-juice-330ml/s/500918"],
    dataNotes:
      "Nutrition figures are high-confidence — Barakat's own product page for this exact barcode matches Open Food Facts and Talabat independently. The single-ingredient listing is inferred from Barakat's labeling pattern on sibling single-fruit juices (no source publishes a verbatim ingredients panel for this exact SKU) — treat as very likely correct, not fully confirmed against the physical label.",
  },

  /**
   * Catalogue expansion — 26 SKUs (8 Calo-brand + 18 spreadsheet-brand),
   * added 2026-08-19. Full research trail: research/calo-brand-skus.md and
   * research/spreadsheet-brand-skus.md. Every field tagged "(estimate)" in
   * dataNotes below was a genuine gap in the source data, filled with
   * Vedant's explicit sign-off and a stated method (scaled reference-food
   * data, direct ingredient reads, or commercial-analog data) — never a
   * silent guess. Two SKUs Vedant approved into this batch were later
   * dropped (Aljazira Golden Eggs, Modern Bakery Sesame Roll) and do not
   * appear here.
   */

  // ---- Calo-brand SKUs (8) ----
  {
    id: "yalla-yum-freeze-dried-strawberry-30g",
    barcode: "642461375497",
    name: "Freeze Dried Strawberry",
    brand: "Yalla Yum",
    category: "snacks",
    servingLabel: "30g (1 pouch)",
    servingSizeG: 30,
    isCaloMarket: true,
    priceAED: 28.86,
    image: "assets/catalogue/yalla-yum-freeze-dried-strawberry.png",
    nutrition: { calories: 109, sugar_g: 18.8, satFat_g: 0, sodium_mg: 0, fiber_g: 7.5, protein_g: 3.8 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["Single ingredient — 100% strawberries, no additives", "Very high fiber for a fruit snack (7.5g per pouch)", "No sodium, no fat"],
    verdict:
      "Just strawberries, no additives — but freeze-drying concentrates natural sugar. A real fruit snack, still worth portioning.",
    ingredients: [{ name: "Strawberries", flag: null, reason: "100% strawberries, no additives — the only ingredient." }],
    dataConfidence: "medium",
    sourceUrls: [
      "https://market.calo.app/en-ae/product/bf9bfd7c-d7f8-4b54-a023-45eb47b391c5",
      "https://organicfoodsandcafe.com/product/yalla-yum-freeze-dried-strawberry-8g",
      "https://www.yallayum.ae/shop/freeze-dried-strawberry",
    ],
    dataNotes:
      "Barcode approved by Vedant (2026-08-19), originally surfaced only as an Organic Foods & Café SKU number, not independently validated as a real EAN/UPC. Nutrition is the reliably-sourced 8g-label figures scaled to the 30g pouch Calo actually sells (Calo's own 240g/960kcal listing has a data-entry bug — an exact 8x multiple of the expected values — and was not used). Allergens (estimate): none apparent, based on the single confirmed ingredient.",
  },
  {
    id: "frio-strawberry-sparkling-water-250ml",
    barcode: "792105023564",
    name: "Strawberry Sparkling Mineral Water",
    brand: "Frio",
    category: "beverages",
    servingLabel: "250ml (1 can)",
    servingSizeG: 250,
    isCaloMarket: true,
    priceAED: 8.4,
    image: "assets/catalogue/frio-strawberry-330ml.png",
    nutrition: { calories: 0, sugar_g: 0, satFat_g: 0, sodium_mg: 4, fiber_g: 0, protein_g: 0 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["Zero calories, sugar, and fat", "Only 2 ingredients"],
    verdict:
      "Carbonated mineral water and natural strawberry flavor — nothing else. Every macro is zero.",
    ingredients: [
      { name: "Carbonated Mineral Water", flag: null, reason: "" },
      { name: "Natural Strawberry Flavour", flag: null, reason: "" },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://market.calo.app/en-ae/product/83d455a2-0276-4009-a9d4-8f553381ac14", "https://frio.ae/products/strawberry-sparkling-water"],
    dataNotes:
      "Barcode provided by Vedant (2026-08-19), not independently verified. Sodium (estimate): ~4mg, derived from this water source's own published mineral-composition figure (15mg/L), not a Nutrition Facts panel value. Allergens (estimate): none apparent, from the 2-ingredient list.",
  },
  {
    id: "frio-mango-sparkling-water-250ml",
    barcode: "792105023571",
    name: "Mango Sparkling Mineral Water",
    brand: "Frio",
    category: "beverages",
    servingLabel: "250ml (1 can)",
    servingSizeG: 250,
    isCaloMarket: true,
    priceAED: 8.4,
    image: "assets/catalogue/frio-mango-330ml.png",
    nutrition: { calories: 0, sugar_g: 0, satFat_g: 0, sodium_mg: 4, fiber_g: 0, protein_g: 0 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["Zero calories, sugar, and fat", "Only 3 ingredients"],
    verdict:
      "Same clean profile as Frio Strawberry — carbonated water and natural mango flavor, every macro at zero.",
    ingredients: [
      { name: "Carbonated Water", flag: null, reason: "" },
      { name: "Natural Mango Flavour", flag: null, reason: "" },
      { name: "Other Natural Flavour", flag: null, reason: "" },
    ],
    dataConfidence: "medium-high",
    sourceUrls: ["https://market.calo.app/en-ae/product/3373f01e-0154-4941-9f67-06521e63203e", "https://frio.ae/products/frio-natural-mango-sparkling-water-6-pack-x-330-ml"],
    dataNotes:
      "Barcode provided by Vedant (2026-08-19), not independently verified — no barcode found anywhere, including Open Food Facts. Sodium (estimate): ~4mg, same water-source reasoning as Frio Strawberry. Allergens (estimate): none apparent.",
  },
  {
    id: "hala-pop-tangerine-250ml",
    barcode: "5287002829036",
    name: "Prebiotic Soda — Tangerine",
    brand: "Hala Pop",
    category: "beverages",
    servingLabel: "250ml (1 can)",
    servingSizeG: 250,
    isCaloMarket: true,
    priceAED: 11.95,
    image: "assets/catalogue/hala-pop-tangerine-250ml.png",
    nutrition: { calories: 29, sugar_g: 3.8, satFat_g: 0, sodium_mg: 50, fiber_g: 6, protein_g: 0.1 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["6g fiber per can from a real fiber blend (cassava, topinambur, baobab)", "Low sugar (3.8g) for a flavored soda", "Sweetened with stevia, not added sugar"],
    verdict:
      "6g fiber, low sugar, sweetened with stevia — a genuinely different profile from a normal soda.",
    ingredients: [
      { name: "Sparkling Water", flag: null, reason: "" },
      { name: "Cassava Fiber", flag: null, reason: "Part of the fiber blend driving this product's 6g fiber per can." },
      { name: "Topinambur Powder", flag: null, reason: "" },
      { name: "Baobab Fruit Pulp", flag: null, reason: "" },
      { name: "Moringa Extract", flag: null, reason: "" },
      { name: "Fruit Juice Concentrates (apple, lemon, grape, pear, tangerine)", flag: null, reason: "" },
      { name: "Natural Flavorings (mandarin, grapefruit)", flag: null, reason: "" },
      { name: "Stevia (Steviol Glycosides)", flag: "caution", reason: "Plant-derived sweetener, generally well tolerated — flagged for visibility since it's a non-sugar sweetener, not a health concern." },
      { name: "Beta Carotene", flag: null, reason: "Natural colorant, also a source of vitamin A." },
      { name: "Antioxidant (Vitamin C)", flag: null, reason: "" },
    ],
    dataConfidence: "medium-high",
    sourceUrls: ["https://market.calo.app/en-ae/product/4ca38879-611f-4f9b-8324-1c576862fbb3", "https://drinkhalapop.com/collections/all/products/tangerine"],
    dataNotes:
      "Barcode provided by Vedant (2026-08-19) for the standalone 250ml can, distinct from a 4-pack SKU this research also found. Allergens (estimate): none apparent, based on the confirmed ingredient list — 'vegan friendly' marketing wasn't used as the basis. Price has real conflicting figures across retailers (9.95–11.95 AED); used Calo's own storefront price.",
  },
  {
    id: "plaay-triple-chocolate-truffles-30g",
    barcode: "6298044154214",
    name: "Triple Chocolate Truffles",
    brand: "Plaay",
    category: "snacks",
    servingLabel: "30g (2 truffles)",
    servingSizeG: 30,
    isCaloMarket: true,
    priceAED: 19.9,
    image: "assets/catalogue/plaay-triple-chocolate-truffles-30g.jpg",
    nutrition: { calories: 81, sugar_g: 0, satFat_g: 0, sodium_mg: 12, fiber_g: 0, protein_g: 2 },
    allergens: ["tree_nuts", "dairy"],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["Contains a live probiotic culture (2.5 billion CFU per pack)", "Sweetened with dates, not refined sugar"],
    verdict:
      "Sweetened with dates and boosted with whey protein and a probiotic culture — though 0g sugar is surprising given dates are a listed ingredient.",
    ingredients: [
      { name: "Hazelnuts", flag: "concern", reason: "Tree nut — major allergen, can trigger severe reactions in people with a tree nut allergy." },
      { name: "71% Vegan Dark Chocolate (cacao mass, cocoa butter, coconut sugar, sunflower lecithin)", flag: null, reason: "" },
      { name: "Dates", flag: null, reason: "Natural whole-fruit sweetener." },
      { name: "Cocoa Powder", flag: null, reason: "" },
      { name: "Grass Fed Whey Protein", flag: null, reason: "Dairy-derived — declared allergen source." },
      { name: "Prebiotic Inulin Fiber", flag: null, reason: "" },
      { name: "Probiotic Bacillus Coagulans", flag: null, reason: "Live bacterial culture, 2.5 billion CFU per pack." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://shopplaay.com/products/triple-chocolate-truffles-10x30g", "https://www.sporter.com/en-ae/plaay-triple-chocolate-truffles-pack-of-10/"],
    dataNotes:
      "Barcode chosen by Vedant (2026-08-19) from 3 candidates this research found. Price set by Vedant at 19.90 AED (no usable Calo-listed price was found — this item is only listed on Calo's Bahrain/Qatar storefronts, not UAE). Sodium is a single low-confidence third-party figure (5.79mg/15g, Cyclesouq) — not independently corroborated, flagged accordingly. Sugar (0g) is as directly stated by Calo across both pack sizes, despite dates being a named ingredient — reported as given, not adjusted.",
  },
  {
    id: "calo-caramel-protein-popcorn-50g",
    barcode: "6294005102645",
    name: "Caramel Protein Popcorn",
    brand: "Store Brand",
    category: "snacks",
    servingLabel: "50g (1 pack)",
    servingSizeG: 50,
    isCaloMarket: true,
    priceAED: 21,
    image: "assets/catalogue/calo-caramel-protein-popcorn.png",
    nutrition: { calories: 199, sugar_g: 18.9, satFat_g: 1.3, sodium_mg: 255, fiber_g: 2, protein_g: 11 },
    allergens: ["dairy", "soy"],
    mayContainAllergens: [],
    concernMarkers: [
      "Sugar is high once normalized — 37.8g per 100g",
      "Sodium is an estimate — this product's own label doesn't disclose it, unusually for a packaged snack",
    ],
    positiveFlags: ["11g protein per pack from real whey protein"],
    verdict:
      "11g of real whey protein is genuine — but 37.8g sugar per 100g makes this a caramel treat first, protein snack second.",
    ingredients: [
      { name: "Cream of Tartar", flag: null, reason: "" },
      { name: "Salt (Fine)", flag: null, reason: "" },
      { name: "Jaggery", flag: "caution", reason: "Unrefined cane sugar — a major contributor to this product's sugar content, alongside the corn syrup solids and added sugar below." },
      { name: "Mushroom Corn (for Popcorn)", flag: null, reason: "" },
      { name: "Water", flag: null, reason: "" },
      { name: "Whey Protein", flag: null, reason: "Dairy-derived — declared allergen source." },
      { name: "Cream", flag: null, reason: "Dairy — declared allergen source." },
      { name: "Butter", flag: null, reason: "Dairy — declared allergen source." },
      { name: "Non-Hydrogenated Soybean Oil", flag: null, reason: "Soy-derived — declared allergen source." },
      { name: "Lecithin (E322)", flag: "caution", reason: "Emulsifier, soy-derived — declared allergen source." },
      { name: "Corn Syrup Solids", flag: "caution", reason: "Refined added sugar." },
      { name: "Soybean", flag: null, reason: "Declared allergen source." },
      { name: "Sugar", flag: "caution", reason: "Directly added refined sugar, on top of jaggery and corn syrup solids." },
    ],
    dataConfidence: "medium-high",
    sourceUrls: ["https://market.calo.app/en-ae/product/2457ee1a-f97e-4de5-94f5-d473e76fbfb2", "https://market.calo.app/en-ae/product/c509c340-2431-4a69-a55e-f27f7c5f2a0b"],
    dataNotes:
      "Barcode provided by Vedant (2026-08-19), not independently verified. Sodium (estimate): ~255mg, from USDA's generic 'caramel coated popcorn' reference (511mg/100g) scaled to 50g — genuinely absent from Calo's own disclosure on both SKUs this research checked. Allergens (Contains Milk, Soy) are a direct read of the ingredient list, not a formal 'Contains' box.",
  },
  {
    id: "calo-protein-chocolate-200ml",
    barcode: "0000000000021",
    name: "Protein Chocolate Drink",
    brand: "Store Brand",
    category: "milk_milk_alternatives",
    servingLabel: "200ml (1 bottle)",
    servingSizeG: 200,
    isCaloMarket: true,
    priceAED: 14.18,
    image: "assets/catalogue/calo-protein-chocolate-200ml.png",
    nutrition: { calories: 147, sugar_g: 0, satFat_g: 0, sodium_mg: 110, fiber_g: 0, protein_g: 20 },
    allergens: ["dairy", "soy"],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["20g protein in a 200ml drink", "0g sugar, sweetened with monk fruit instead"],
    verdict:
      "20g protein, 0g sugar — sweetened with monk fruit instead. One of the cleanest protein drinks here.",
    ingredients: [
      { name: "Soy Milk", flag: null, reason: "Declared allergen source (soy)." },
      { name: "Whipping Cream", flag: null, reason: "Dairy — declared allergen source." },
      { name: "Monk Fruit Sweetener", flag: null, reason: "Natural, non-caloric sweetener — the reason this drink shows 0g sugar despite tasting sweet." },
      { name: "Protein Powder (Vanilla)", flag: null, reason: "" },
      { name: "Cocoa Powder", flag: null, reason: "" },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://market.calo.app/en-ae/product/888cf8be-3218-471b-8732-ffcd3c603566"],
    dataNotes:
      "**Barcode is a placeholder (0000000000021), not real — Vedant explicitly authorized a dummy barcode (2026-08-19) since no real one exists for this SKU anywhere (checked Calo's own pages, Open Food Facts, Amazon.ae, noon.com, Talabat). Must never be presented as verified data — it exists only so the app's scan flow has something to match.** Sodium (estimate): ~110mg — the weakest-grounded number in this entire catalogue, a category analogy to Nada's protein milk rather than a scaled reference food; flag this one first if precision ever matters. Allergens (Contains Milk, Soy) are a direct read of the ingredient list.",
  },
  {
    id: "soul-pantry-tuscan-tomato-chips-50g",
    barcode: "0000000000022",
    name: "Tuscan Tomato Protein Chips",
    brand: "Soul Pantry",
    category: "snacks",
    servingLabel: "50g (1 pack)",
    servingSizeG: 50,
    isCaloMarket: true,
    priceAED: 7.35,
    image: "assets/catalogue/soul-pantry-tuscan-tomato-chips.png",
    nutrition: { calories: 192, sugar_g: 0, satFat_g: 0.04, sodium_mg: 320, fiber_g: 5.5, protein_g: 15 },
    allergens: [],
    mayContainAllergens: ["wheat", "soy", "dairy", "tree_nuts"],
    concernMarkers: ["Sodium is an estimate, and if accurate it's on the high side for the pack size"],
    positiveFlags: ["15g plant protein per pack", "5.5g fiber per pack", "0g sugar", "Baked, not fried (0.04g saturated fat)"],
    verdict:
      "High protein, high fiber, no sugar, baked not fried. Sodium isn't disclosed and may run high.",
    ingredients: [
      { name: "Pea Protein Isolate", flag: null, reason: "" },
      { name: "Brown Rice Protein", flag: null, reason: "" },
      { name: "Green Gram Protein", flag: null, reason: "" },
      { name: "Rice Grits", flag: null, reason: "" },
      { name: "Corn Grits", flag: null, reason: "" },
      { name: "Chickpea Flour", flag: null, reason: "" },
      { name: "Rice Bran Oil", flag: null, reason: "" },
      { name: "Salt", flag: "caution", reason: "Main driver of the sodium content this label doesn't disclose a number for." },
      { name: "Tomato Powder", flag: null, reason: "" },
      { name: "Onion Powder", flag: null, reason: "" },
      { name: "Garlic Powder", flag: null, reason: "" },
      { name: "Chilli Powder", flag: null, reason: "" },
      { name: "Maltodextrin", flag: "caution", reason: "Refined starch-derived filler — digests quickly despite not being a sugar." },
      { name: "Acidity Regulators (E262(ii), E330, E334)", flag: "caution", reason: "Permitted additives; flagged for visibility." },
      { name: "Emulsifier & Stabilizer (E415)", flag: "caution", reason: "Permitted additive; flagged for visibility." },
      { name: "Anticaking Agent (E551)", flag: null, reason: "" },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://soulpantry.co/product/tuscan-tomato-protein-chips-2/", "https://market.calo.app/en-ae/product/28234f6b-9356-449f-930e-b00b95e6f20a"],
    dataNotes:
      "**Barcode is a placeholder (0000000000022), not real — Vedant explicitly authorized a dummy barcode (2026-08-19). Must never be presented as verified data.** Sodium (estimate): ~320mg, by analogy to Quest Chili Lime Chips (a similarly-styled baked protein chip), scaled by weight — order-of-magnitude, not precise; genuinely absent from every source including the brand's own site, despite salt being a named ingredient. 'May contain wheat, soy, milk and traces of nuts' is a real single-sourced cross-contact statement (sqoon.co), not a direct ingredient — kept in mayContainAllergens rather than allergens for that reason.",
  },

  // ---- Spreadsheet-brand SKUs (18) ----
  {
    id: "rubicon-coconut-water-250ml",
    barcode: "64579330753",
    name: "Organic Coconut Water",
    brand: "Rubicon",
    category: "beverages",
    servingLabel: "250ml",
    servingSizeG: 250,
    isCaloMarket: true,
    priceAED: 18,
    image: "assets/catalogue/rubicon-coconut-water-1l.jpg",
    nutrition: { calories: 43, sugar_g: 6.3, satFat_g: 0.3, sodium_mg: 73, fiber_g: 0, protein_g: 1.25 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["Single ingredient — 100% organic coconut water", "Natural source of electrolytes"],
    verdict:
      "One ingredient, nothing added — a natural source of potassium and other electrolytes.",
    ingredients: [{ name: "100% Organic Coconut Water", flag: null, reason: "Single ingredient, confirmed on 3 independent sources." }],
    dataConfidence: "medium",
    sourceUrls: ["https://organicfoodsandcafe.com", "https://images.openfoodfacts.org/images/products/006/457/933/0753/front_en.11.400.jpg"],
    dataNotes:
      "Open Food Facts' own record for this barcode has conflicting nutrition that looks copy-pasted from a sibling SKU — used SKU-matched retailer data instead, corroborated by two independent retailers. Fiber (estimate): 0g, not disclosed by any source but structurally near-certain for a clear coconut water. Allergens (estimate): none apparent. Price shown is the midpoint of a real 15.75–21.00 AED retailer range.",
  },
  {
    id: "red-bull-energy-drink-250ml",
    barcode: "90162602",
    name: "Energy Drink",
    brand: "Red Bull",
    category: "beverages",
    servingLabel: "250ml (1 can)",
    servingSizeG: 250,
    isCaloMarket: false,
    priceAED: 9.99,
    image: "assets/catalogue/red-bull-classic-250ml.jpg",
    nutrition: { calories: 113, sugar_g: 27.5, satFat_g: 0, sodium_mg: 98, fiber_g: 0, protein_g: 0 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: ["27.5g sugar in one can — a meaningful share of a day's sugar budget", "High caffeine content, not appropriate for children or in multiples per day"],
    positiveFlags: [],
    verdict:
      "An energy drink, not a health product — 27.5g sugar and real caffeine in one can. Fine occasionally, not daily.",
    ingredients: [
      { name: "Carbonated Water", flag: null, reason: "" },
      { name: "Sugar", flag: "caution", reason: "Primary driver of this product's 27.5g sugar per can." },
      { name: "Glucose", flag: "caution", reason: "Additional added sugar alongside sucrose." },
      { name: "Citric Acid", flag: null, reason: "" },
      { name: "Taurine", flag: null, reason: "Amino acid, standard energy-drink ingredient — well studied at typical intake levels." },
      { name: "Natural Flavors", flag: null, reason: "" },
      { name: "Artificial Flavors", flag: "caution", reason: "" },
      { name: "Sodium Bicarbonate", flag: null, reason: "" },
      { name: "Magnesium Carbonate", flag: null, reason: "" },
      { name: "Artificial Colors", flag: "caution", reason: "Synthetic colorants — permitted, some consumers prefer to avoid them." },
      { name: "Caffeine", flag: "caution", reason: "Stimulant — the main reason moderation and age-appropriateness matter for this category." },
      { name: "Niacinamide", flag: null, reason: "Vitamin B3, fortification." },
      { name: "Pyridoxine HCl", flag: null, reason: "Vitamin B6, fortification." },
      { name: "Calcium Pantothenate", flag: null, reason: "Vitamin B5, fortification." },
      { name: "Vitamin B12", flag: null, reason: "Fortification." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://world.openfoodfacts.org/product/90162602", "https://www.nutritionvalue.org"],
    dataNotes:
      "This OFF barcode's listed sale countries don't include UAE, so treat this as representative of the Classic formulation rather than confirmed UAE packaging — Redbull.com's own US figures (110kcal/26g sugar/105mg sodium per 250ml) are in the same ballpark, not identical. Fiber (estimate): 0g. Allergens (estimate): none apparent.",
  },
  {
    id: "al-rawabi-mango-juice-250ml",
    barcode: "6291030004661",
    name: "Mango Juice",
    brand: "Al Rawabi",
    category: "beverages",
    servingLabel: "250ml",
    servingSizeG: 250,
    isCaloMarket: false,
    priceAED: 12.99,
    image: "assets/catalogue/al-rawabi-mango-juice.png",
    nutrition: { calories: 138, sugar_g: 28, satFat_g: 0.5, sodium_mg: 25, fiber_g: 0, protein_g: 0.5 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: ["28g sugar per 250ml serving, from a stabilized/reconstituted juice, not the plain fruit"],
    positiveFlags: [],
    verdict:
      "A sweetened, stabilized juice, not whole fruit — 28g sugar per serving, notably more than the fresh-squeezed juices here.",
    ingredients: [
      { name: "Water", flag: null, reason: "" },
      { name: "Sugar", flag: "caution", reason: "Added sugar, on top of the natural sugar in mango pulp — primary driver of this product's 28g sugar per serving." },
      { name: "Mango Pulp", flag: null, reason: "" },
      { name: "Stabilizers (E412, E466)", flag: "caution", reason: "Permitted thickening/stabilizing additives." },
      { name: "Acidifier (E330)", flag: null, reason: "Common, well-tolerated acidity regulator." },
      { name: "Nature Identical Mango Flavour", flag: "caution", reason: "Synthetic flavoring matching the natural compound, not real mango flavor." },
      { name: "Antioxidant (E300)", flag: null, reason: "Vitamin C, used as a preservative." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://noon.com", "https://carrefouruae.com"],
    dataNotes:
      "**The barcode itself was never displayed on any source found** — this match rests on name/brand/size correspondence, not a direct barcode confirmation; Open Food Facts blocks this research entirely via robots.txt. Ingredients are from Al Rawabi's 800ml pack of the same line, not independently confirmed identical for this 1.5L SKU. satFat and sodium (estimates): used the '<0.5g' and '<10mg' upper bounds reported by the source as point figures. Allergens (estimate): none apparent. Price shown is the midpoint of a 12.29–13.50 AED range.",
  },
  {
    id: "nescafe-spanish-latte-iced-coffee-225ml",
    barcode: "8992696526037",
    name: "Spanish Latte Iced Coffee",
    brand: "Nescafe",
    category: "beverages",
    servingLabel: "225ml (1 can)",
    servingSizeG: 225,
    isCaloMarket: false,
    priceAED: 5.25,
    image: "assets/catalogue/nescafe-iced-coffee-225ml.png",
    nutrition: { calories: 140, sugar_g: 20.25, satFat_g: 1.8, sodium_mg: 135, fiber_g: 1.1, protein_g: 6 },
    allergens: ["dairy", "soy"],
    mayContainAllergens: [],
    concernMarkers: ["20g+ sugar in one can — a meaningful share of a day's sugar budget from a coffee drink"],
    positiveFlags: ["6g protein per can from real milk"],
    verdict:
      "Real dairy protein, but also real added sugar — 20g in one can, closer to dessert-coffee than plain iced coffee.",
    ingredients: [
      { name: "Cow's Milk (75%) (Water, Skimmed Milk, Milk Fat)", flag: null, reason: "Declared allergen source (milk)." },
      { name: "Sugar", flag: "caution", reason: "Primary driver of this product's 20g+ sugar per can." },
      { name: "Soluble Coffee", flag: null, reason: "" },
      { name: "Stabilizers (E500ii, E460i, E466, E332ii)", flag: "caution", reason: "Permitted additives; flagged for visibility." },
      { name: "Cocoa Powder", flag: null, reason: "" },
      { name: "Coffee Flavors", flag: "caution", reason: "" },
      { name: "Emulsifier (Soya Lecithin)", flag: null, reason: "Declared allergen source (soy)." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://world.openfoodfacts.org/product/8992696526037", "https://nescafe.com"],
    dataNotes:
      "Sodium (estimate): ~135mg — Open Food Facts' own figure (0.1mg/100ml) is an implausible unit error for a dairy product; used the midpoint of the typical 40-80mg/100ml range for ready-to-drink dairy iced coffee instead. Fiber (0.5g/100ml as found) is also flagged upstream as suspect for a drink with no fiber source, but reported as found rather than overridden.",
  },
  {
    id: "barakat-beetroot-orange-juice-200ml",
    barcode: "6291100930302",
    name: "Fresh Beetroot Orange Juice",
    brand: "Barakat",
    category: "beverages",
    servingLabel: "200ml",
    servingSizeG: 200,
    isCaloMarket: true,
    priceAED: 5.8,
    image: "assets/catalogue/barakat-beetroot-orange-200ml.jpg",
    nutrition: { calories: 70, sugar_g: 16, satFat_g: 0, sodium_mg: 30, fiber_g: 2, protein_g: 2 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [],
    positiveFlags: ["Just two whole-food ingredients — beetroot and orange", "2g fiber per serving, unusual for a juice"],
    verdict:
      "Two whole-food ingredients, no additives, and real fiber most juices strip out. Still naturally sweet at 16g sugar.",
    ingredients: [
      { name: "Beetroot", flag: null, reason: "" },
      { name: "Orange", flag: null, reason: "" },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://barakatfresh.ae"],
    dataNotes:
      "Product image filename on the brand's own site literally contains this barcode, confirming the match. Open Food Facts' record for this exact barcode shows very different numbers and looks like a low-quality stale community entry — used the brand's own site instead. Allergens (estimate): none apparent.",
  },
  {
    id: "kelloggs-frosties-cereal-30g",
    barcode: "5059319024448",
    name: "Frosties Cereal",
    brand: "Kellogg's",
    category: "breakfast",
    servingLabel: "30g",
    servingSizeG: 30,
    isCaloMarket: false,
    priceAED: 34.7,
    image: "assets/catalogue/kelloggs-frosties-750g.jpg",
    nutrition: { calories: 113, sugar_g: 11, satFat_g: 0, sodium_mg: 100, fiber_g: 0.6, protein_g: 1.4 },
    allergens: [],
    mayContainAllergens: ["peanut"],
    concernMarkers: [
      "37g sugar per 100g — more than a third of the cereal by weight is sugar",
      "Barley, a gluten-containing grain, is a core ingredient — flagged as an allergen source even though this app's allergy list doesn't have a dedicated 'barley' or 'gluten' category to select",
    ],
    positiveFlags: [],
    verdict:
      "Over a third sugar by weight — more than most candy-adjacent snacks here. A dry 30g bowl is a small pour.",
    ingredients: [
      { name: "Maize", flag: null, reason: "" },
      { name: "Sugar", flag: "caution", reason: "Primary driver of this cereal's 37g sugar per 100g — the single largest contributor to its low score." },
      { name: "Barley Malt Extract", flag: null, reason: "Contains gluten — declared allergen source; this app's allergen list doesn't currently have a 'barley' or 'gluten' option distinct from wheat, worth flagging as a taxonomy gap." },
      { name: "Salt", flag: null, reason: "" },
    ],
    dataConfidence: "high",
    sourceUrls: ["https://world.openfoodfacts.org/product/5059319024448", "https://kelloggs-me.com"],
    dataNotes:
      "High confidence — barcode-matched on Open Food Facts, corroborated by Kellogg's own Middle East site for ingredients/allergens. Kellogg's ME's own sizing page doesn't list 470g among stated pack sizes, suggesting this is a UK-import/value-pack variant sold in UAE — 6 independent UAE retailers confirm it's real regardless. This SKU's real allergen is barley (gluten), which doesn't map to this app's current allergen taxonomy (eggs/dairy/soy/peanut/tree_nuts/fish/shellfish/sesame/wheat) — left out of the allergens field rather than mis-tagged as 'wheat,' which this product doesn't actually contain.",
  },
  {
    id: "brod-sourdough-bread-250g",
    barcode: "6291003648335",
    name: "Small Sourdough Bread",
    brand: "Brod",
    category: "fresh_bakery",
    servingLabel: "250g (1 loaf)",
    servingSizeG: 250,
    isCaloMarket: true,
    priceAED: 9.95,
    image: "assets/catalogue/brod-sourdough-bread-250g.png",
    nutrition: { calories: 680, sugar_g: 11.5, satFat_g: 1.3, sodium_mg: 1505, fiber_g: 5.5, protein_g: 27 },
    allergens: ["wheat"],
    mayContainAllergens: ["soy", "dairy", "tree_nuts"],
    concernMarkers: ["Sodium is high for a full loaf — bread is naturally salt-heavy, and this is an estimate, not Brod's own measured figure"],
    positiveFlags: ["27g protein and 5.5g fiber across the loaf"],
    verdict:
      "No published nutrition panel for this SKU — figures are a generic sourdough reference, not Brod's own data.",
    ingredients: [
      { name: "Unbleached Enriched Wheat Flour (wheat flour, malted barley flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid)", flag: null, reason: "Contains gluten — declared allergen source." },
      { name: "Water", flag: null, reason: "" },
      { name: "Sour Culture (Sourdough Starter)", flag: null, reason: "" },
      { name: "Salt", flag: "caution", reason: "Main driver of this bread's high estimated sodium." },
      { name: "Semolina", flag: null, reason: "Wheat-derived." },
    ],
    dataConfidence: "low",
    sourceUrls: ["https://foodisgood.com/product/la-brea-bakery-sourdough-bread-loaf/", "https://tools.myfooddata.com"],
    dataNotes:
      "**Entire nutrition profile is an estimate**, per Vedant's explicit authorization (2026-08-19) to use credible generic data 'modified by weight': USDA's 'Bread, french or vienna, includes sourdough' reference food, scaled ×2.5 from its per-100g values to this 250g loaf. Ingredients/allergens are similarly borrowed from a real commercial sourdough product (La Brea Bakery), also per Vedant's instruction to use a similar alternative rather than assume — not Brod's own recipe. High-confidence only on identity, price, and image; low on everything nutrition-related.",
  },
  {
    id: "krispy-kreme-minis-doughnut-30g",
    barcode: "1002000000010",
    name: "Minis Doughnuts",
    brand: "Krispy Kreme",
    category: "fresh_bakery",
    servingLabel: "30g (1 mini doughnut)",
    servingSizeG: 30,
    isCaloMarket: false,
    priceAED: 16.5,
    image: "assets/catalogue/krispy-kreme-doughnuts.png",
    nutrition: { calories: 97, sugar_g: 5.5, satFat_g: 2.45, sodium_mg: 140, fiber_g: 0.33, protein_g: 1.37 },
    allergens: ["wheat", "dairy", "eggs", "soy"],
    mayContainAllergens: [],
    concernMarkers: [
      "Saturated fat is high per 100g (8.2g) for what looks like a small, innocuous mini",
      "Sugar and sodium are both estimates, not this SKU's own disclosed figures",
    ],
    positiveFlags: [],
    verdict:
      "A fried, glazed treat — the 'mini' size doesn't change what it's made of. Easy to eat several in one sitting.",
    ingredients: [
      { name: "Enriched Wheat Flour", flag: null, reason: "Contains gluten — declared allergen source." },
      { name: "Sugar", flag: "caution", reason: "" },
      { name: "Water", flag: null, reason: "" },
      { name: "Yeast", flag: null, reason: "" },
      { name: "Vegetable Oil/Shortening", flag: "caution", reason: "Frying/dough fat — main driver of this product's high saturated fat." },
      { name: "Glaze (Sugar, Water)", flag: "caution", reason: "" },
      { name: "Egg", flag: null, reason: "Declared allergen source." },
      { name: "Milk/Whey", flag: null, reason: "Declared allergen source." },
      { name: "Soybean Oil / Soy Lecithin", flag: null, reason: "Declared allergen source." },
      { name: "Salt", flag: null, reason: "" },
    ],
    dataConfidence: "low",
    sourceUrls: ["https://minutes.noon.com", "https://godairyfree.org/dining-out/dunkin-donuts", "https://tools.myfooddata.com/nutrition-facts/174990/wt1"],
    dataNotes:
      "**Barcode is structurally suspect** (passes GTIN-13 checksum but an atypical GS1 prefix, unresolvable on Open Food Facts) — Vedant confirmed use as-is anyway (2026-08-19). Pack size confirmed as 10 pieces. Calories/satFat/fiber/protein from a single noon.com listing. Sugar and sodium (estimates): scaled from USDA's generic 'Doughnuts, cake-type, plain' reference (18.25g sugar, 477mg sodium per 100g) — Krispy Kreme's actual product is yeast-leavened/glazed, not cake-type, so treat these as approximate. Ingredients/allergens (estimate): sourced from Dunkin' Donuts' official chain-wide allergen statement ('contains milk, wheat, egg, and soy') and a representative glazed-doughnut composition, per Vedant's instruction to use a commercial-chain analog — not Krispy Kreme's own published recipe. Ships as isCaloMarket: false per Vedant's standing 'unhealthy items shouldn't be on Market' instruction, same as 7Days Croissant.",
  },
  {
    id: "id-whole-wheat-parota-80g",
    barcode: "8906020580145",
    name: "Fresh Whole Wheat Parota",
    brand: "ID",
    category: "longer_life_bakery",
    servingLabel: "80g (1 piece)",
    servingSizeG: 80,
    isCaloMarket: true,
    priceAED: 6.7,
    image: "assets/catalogue/id-whole-wheat-parota-400g.png",
    nutrition: { calories: 240, sugar_g: 0, satFat_g: 4, sodium_mg: 168, fiber_g: 2.4, protein_g: 5.6 },
    allergens: ["wheat", "sesame"],
    mayContainAllergens: [],
    concernMarkers: ["Saturated fat (5g/100g) is high — the layered, oil-laminated dough is the reason"],
    positiveFlags: ["No added sugar", "2.4g fiber per piece from whole wheat flour"],
    verdict:
      "The oil-laminated layers that make it satisfying also push saturated fat to the edge of high. Real fiber from whole wheat.",
    ingredients: [
      { name: "Whole Wheat Flour (Atta, 52.75%)", flag: null, reason: "Contains gluten — declared allergen source." },
      { name: "RO-Purified Water", flag: null, reason: "" },
      { name: "Edible Vegetable Oil (Rice Bran/Soyabean/Coconut/Sesame Oil)", flag: null, reason: "Contains sesame oil — declared allergen source; also the main driver of this product's saturated fat." },
      { name: "Iodised Salt", flag: null, reason: "" },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://world.openfoodfacts.org/product/8906020580145"],
    dataNotes:
      "**Open Food Facts lists this exact barcode under the name 'Wheat Lachha Parantha,' not 'Whole Wheat Parota'** — typically distinct products from the same manufacturer. Vedant confirmed using the Lachha Paratha data as-is (2026-08-19); worth a physical-pack check before presenting this name to Ahmed if it comes up. Price (6.70 AED) is from a similar but not barcode-confirmed 'iD Frozen Whole Wheat Parota 5pcs 400g' listing — not verified identical to this exact SKU.",
  },
  {
    id: "yakult-probiotic-drink-80ml",
    barcode: "4806509936453",
    name: "Probiotic Drink — Plain",
    brand: "Yakult",
    category: "milk_milk_alternatives",
    servingLabel: "80ml (1 bottle)",
    servingSizeG: 80,
    isCaloMarket: true,
    priceAED: 17.2,
    image: "assets/catalogue/yakult-probiotic.png",
    nutrition: { calories: 48, sugar_g: 11.3, satFat_g: 0, sodium_mg: 16.3, fiber_g: 0, protein_g: 0.8 },
    allergens: ["dairy"],
    mayContainAllergens: [],
    concernMarkers: ["11g sugar in an 80ml bottle is a lot relative to the size — over 14g per 100ml"],
    positiveFlags: ["Contains a live probiotic culture (Lactobacillus casei Shirota)"],
    verdict:
      "The probiotic culture is real, but so is the sugar — proportionally sweeter than most sodas for the bottle size.",
    ingredients: [{ name: "Fermented Skimmed Milk (with live Lactobacillus casei Shirota culture)", flag: null, reason: "Dairy — declared allergen source; the product's own category definition, since the exact ingredient list for this specific barcode/region wasn't found." }],
    dataConfidence: "medium",
    sourceUrls: ["https://kanbkam.com", "https://noon.com"],
    dataNotes:
      "Ingredient list not found for this exact barcode/region — UK and India Yakult SKUs have different ingredient orders, so neither was substituted. Allergens (estimate): Contains Milk — a category-level call ('fermented milk drink' by definition), not read off this SKU's own label. satFat (estimate): 0g, structurally near-certain for this famously low-fat product line. Open Food Facts shows this barcode's country of sale as France while UAE retailers list origin as Philippines, explaining a real sodium/protein discrepancy between sources — used UAE-market figures as primary. Price shown is the midpoint of a 16.49–17.95 AED range.",
  },
  {
    id: "nada-chocolate-protein-milk-320ml",
    barcode: "6281018154549",
    name: "Chocolate Low Fat Protein Milk",
    brand: "Nada",
    category: "milk_milk_alternatives",
    servingLabel: "320ml (1 bottle)",
    servingSizeG: 320,
    isCaloMarket: true,
    priceAED: 6.5,
    image: "assets/catalogue/nada-chocolate-protein-milk-320ml.png",
    nutrition: { calories: 192, sugar_g: 40, satFat_g: 0.03, sodium_mg: 138, fiber_g: 0, protein_g: 27 },
    allergens: ["dairy"],
    mayContainAllergens: [],
    concernMarkers: ["40g sugar per bottle — as much sugar as some sodas, despite the 'protein milk' framing"],
    positiveFlags: ["27g protein per bottle, essentially fat-free"],
    verdict:
      "27g protein, but also 40g sugar per bottle — as much as some sodas, despite the 'protein milk' framing.",
    ingredients: [
      { name: "Fresh Cow's Milk (partially skimmed, max 0.05% fat)", flag: null, reason: "Declared allergen source." },
      { name: "Milk Protein", flag: null, reason: "Added to boost protein content — standard dairy ingredient." },
      { name: "Apple & Grape Concentrate", flag: "caution", reason: "Fruit-derived sugar concentrate — a real contributor to this product's 40g sugar per bottle, alongside the cocoa/chocolate sweetening." },
      { name: "Cocoa Powder", flag: null, reason: "" },
      { name: "Chocolate Flavoring", flag: "caution", reason: "" },
      { name: "Stabilizer (E407)", flag: "caution", reason: "Permitted thickener; flagged for visibility." },
      { name: "Preservative (E234)", flag: "caution", reason: "Nisin, a permitted antimicrobial preservative." },
      { name: "Vitamins A and D", flag: null, reason: "Fortification." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://nada.com.sa/en/product/", "https://world.openfoodfacts.org/product/6281018154549"],
    dataNotes:
      "**Protein resolved to 27g per Vedant (2026-08-19)** — the brand's own site states 27g, while Open Food Facts shows a higher 30.4g figure from a different formulation reading; used the brand's own site consistently for all related fields (calories, sugar, sodium) rather than mixing sources. **The product's packaging says '30g Protein' — do not repeat that claim in the app**, since the 27g figure is what this data is built on.",
  },
  {
    id: "hayatna-greek-yoghurt-360g",
    barcode: "6297001135754",
    name: "Greek Yoghurt — 31g Protein",
    brand: "Hayatna",
    category: "other_dairy_products",
    servingLabel: "360g (1 tub)",
    servingSizeG: 360,
    isCaloMarket: true,
    priceAED: 8.65,
    image: "assets/catalogue/hayatna-greek-yoghurt.png",
    nutrition: { calories: 436, sugar_g: 54, satFat_g: 7.2, sodium_mg: 497, fiber_g: 0, protein_g: 31 },
    allergens: ["dairy"],
    mayContainAllergens: [],
    concernMarkers: ["54g sugar across the tub, all of it naturally-occurring lactose (confirmed 0g added sugar on the physical label) — still counts toward your sugar intake regardless of source, and it's meaningfully more than the fat-free Greek yoghurt in this catalogue"],
    positiveFlags: [
      "31g protein per tub, matching the product's own headline claim closely",
      "0g added sugar, confirmed on the physical label — the sugar present is naturally-occurring milk lactose, not an added sweetener",
    ],
    verdict:
      "31g protein, confirmed on the label. But the milk solids that boost protein also concentrate natural sugar (lactose) well above plain yoghurt.",
    ingredients: [
      { name: "Fresh Cow's Milk", flag: null, reason: "Declared allergen source." },
      { name: "Milk Solids", flag: null, reason: "" },
      { name: "Starter Cultures", flag: null, reason: "Standard yoghurt fermentation culture." },
      { name: "Vitamins (A, D3)", flag: null, reason: "Fortification." },
    ],
    dataConfidence: "high",
    sourceUrls: ["https://world.openfoodfacts.org/product/6297001135754", "https://noon.com", "Physical label photo, supplied by Vedant (2026-08-19)"],
    dataNotes:
      "**Confirmed against the physical label (photo supplied by Vedant, 2026-08-19)** — matches the previously-researched figures almost exactly: 121 kcal, 3g total fat, 2g saturated fat, 138mg sodium, 15g total sugar, 8.5g protein per 100g, all per the printed Nutrition Facts panel. Critically, the label states 'Includes 0g Added Sugars' — resolving what was an open question (the ingredient list, milk/milk solids/cultures, didn't obviously explain a sugar figure this high for a 'Greek' style yoghurt, where straining usually lowers sugar vs. regular yoghurt). Now confirmed: all 15g/100g is naturally-occurring milk lactose, not a hidden added sweetener — the milk solids added to reach the '31g protein' claim also concentrate the natural lactose. Confidence raised from medium to high on the strength of this label confirmation. Ingredients themselves remain single-sourced from Open Food Facts, not independently corroborated.",
  },
  {
    id: "cheetos-flamin-hot-crunchy-28g",
    barcode: "28400037174",
    name: "Flamin' Hot Crunchy Cheese Puffs",
    brand: "Cheetos",
    category: "snacks",
    servingLabel: "28g (~21 pieces)",
    servingSizeG: 28,
    isCaloMarket: false,
    priceAED: 12.2,
    image: "assets/catalogue/cheetos-flamin-hot-285g.jpg",
    nutrition: { calories: 160, sugar_g: 0, satFat_g: 1.5, sodium_mg: 246, fiber_g: 1.0, protein_g: 1.0 },
    allergens: ["dairy"],
    mayContainAllergens: [],
    concernMarkers: [
      "Saturated fat is high per 100g (5.4g)",
      "Sodium is very high per 100g (~880mg, or noon.com's own panel implies ~750mg — either way, one of the highest in this catalogue)",
      "Long list of artificial colors and flavor-enhancing additives (MSG, disodium inosinate/guanylate)",
    ],
    positiveFlags: [],
    verdict:
      "A heavily processed snack — sodium runs well into high territory by either disclosed figure, plus a long additive list.",
    ingredients: [
      { name: "Enriched Corn Meal", flag: null, reason: "" },
      { name: "Vegetable Oil", flag: null, reason: "" },
      { name: "Maltodextrin", flag: "caution", reason: "Refined starch-derived filler in the seasoning blend." },
      { name: "Salt", flag: "caution", reason: "Major driver of this product's very high sodium." },
      { name: "Sugar", flag: null, reason: "" },
      { name: "MSG (Monosodium Glutamate)", flag: "caution", reason: "Flavor enhancer — widely considered safe by food safety bodies, some consumers prefer to avoid it." },
      { name: "Yeast Extract", flag: null, reason: "" },
      { name: "Citric Acid", flag: null, reason: "" },
      { name: "Artificial Colors (Red 40, Yellow 6, Yellow 5)", flag: "caution", reason: "Synthetic colorants — some evidence links certain artificial colors to hyperactivity in sensitive children; permitted but frequently flagged." },
      { name: "Cheddar Cheese", flag: null, reason: "Declared allergen source (milk)." },
      { name: "Onion Powder", flag: null, reason: "" },
      { name: "Whey / Whey Protein Concentrate", flag: null, reason: "Declared allergen source (milk)." },
      { name: "Garlic Powder", flag: null, reason: "" },
      { name: "Buttermilk", flag: null, reason: "Declared allergen source (milk)." },
      { name: "Sodium Diacetate", flag: "caution", reason: "Preservative/flavoring, contributes to overall sodium." },
      { name: "Disodium Inosinate", flag: "caution", reason: "Flavor enhancer, often paired with MSG; contributes to sodium." },
      { name: "Disodium Guanylate", flag: "caution", reason: "Flavor enhancer, often paired with MSG; contributes to sodium." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://world.openfoodfacts.org/product/28400037174"],
    dataNotes:
      "Sodium has a real, unresolved ~130mg discrepancy between Open Food Facts (880mg/100g, used here) and noon.com's own panel (implies ~750mg/100g) — both are well into 'high' territory regardless of which is used. Fiber (estimate): ~3.6g/100g, from a comparable US-market Flamin' Hot Cheetos listing, since this SKU's own fiber field is absent. Protein (estimate): scaled directly from the found per-100g figure.",
  },
  {
    id: "takis-fuego-28g",
    barcode: "757528008796",
    name: "Fuego Hot Chili Pepper & Lime Tortilla Chips",
    brand: "Takis",
    category: "snacks",
    servingLabel: "28g serving",
    servingSizeG: 28,
    isCaloMarket: false,
    priceAED: 11.49,
    image: "assets/catalogue/takis-fuego.jpg",
    nutrition: { calories: 150, sugar_g: 1, satFat_g: 2.5, sodium_mg: 420, fiber_g: 1, protein_g: 2 },
    allergens: ["soy"],
    mayContainAllergens: ["eggs", "dairy", "peanut", "wheat"],
    concernMarkers: [
      "Sodium is very high per 100g (~1500mg) — one of the highest in this catalogue",
      "Saturated fat is high per 100g (~8.9g)",
      "Contains TBHQ, a synthetic preservative that's drawn extra regulatory scrutiny in several countries, similar to the BHA flagged in this catalogue's 7Days Croissant",
    ],
    positiveFlags: [],
    verdict:
      "One of the highest-sodium items here by far — a small serving eats into a big share of a day's limit.",
    ingredients: [
      { name: "Corn Flour (processed with lime)", flag: null, reason: "" },
      { name: "Vegetable Oil", flag: null, reason: "" },
      { name: "Seasoning", flag: null, reason: "" },
      { name: "Salt", flag: "caution", reason: "Primary driver of this product's very high sodium content." },
      { name: "Maltodextrin", flag: "caution", reason: "Refined starch-derived filler." },
      { name: "Citric Acid", flag: null, reason: "" },
      { name: "Sugar", flag: null, reason: "" },
      { name: "MSG (Monosodium Glutamate)", flag: "caution", reason: "Flavor enhancer, contributes to sodium load." },
      { name: "Hydrolyzed Soy Protein", flag: null, reason: "Declared allergen source (soy)." },
      { name: "Onion Powder", flag: null, reason: "" },
      { name: "Yeast Extract", flag: null, reason: "" },
      { name: "Red 40 Lake", flag: "caution", reason: "Synthetic colorant." },
      { name: "Yellow 6 Lake", flag: "caution", reason: "Synthetic colorant." },
      { name: "Natural and Artificial Flavors", flag: "caution", reason: "" },
      { name: "Sodium Bicarbonate", flag: "caution", reason: "Contributes to sodium load." },
      { name: "Soybean Oil", flag: null, reason: "Declared allergen source (soy)." },
      { name: "Chili Pepper", flag: null, reason: "" },
      { name: "Disodium Inosinate", flag: "caution", reason: "Flavor enhancer, contributes to sodium load." },
      { name: "Disodium Guanylate", flag: "caution", reason: "Flavor enhancer, contributes to sodium load." },
      { name: "TBHQ", flag: "concern", reason: "Synthetic preservative that has drawn extra regulatory scrutiny in several countries — one of the more commonly flagged food additives, similar to the BHA in this catalogue's 7Days Croissant." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://www.smartlabel.org", "https://world.openfoodfacts.org/product/757528008796"],
    dataNotes:
      "Used the manufacturer's own SmartLabel printed-label feed as primary over Open Food Facts, since OFF's entry is internally inconsistent (its fat sub-components don't sum to its own total-fat field). The barcode wasn't visible on any UAE retail listing checked — UAE price/product match is by name/size only. SmartLabel reflects the US formulation, which may not exactly match a UAE-imported pack.",
  },
  {
    id: "lays-salt-and-vinegar-45g",
    barcode: "6281036115300",
    name: "Salt And Vinegar Potato Chips",
    brand: "Lay's",
    category: "snacks",
    servingLabel: "45g (1 pack)",
    servingSizeG: 45,
    isCaloMarket: false,
    priceAED: 2.95,
    image: "assets/catalogue/lays-salt-vinegar-110g.jpg",
    nutrition: { calories: 238, sugar_g: 0.4, satFat_g: 6.84, sodium_mg: 374, fiber_g: 1.8, protein_g: 2.88 },
    allergens: [],
    mayContainAllergens: [],
    concernMarkers: [
      "Saturated fat is very high per 100g (15.2g) — one of the highest in this catalogue",
      "Sodium is high per 100g (832mg)",
    ],
    positiveFlags: ["No meaningful sugar"],
    verdict:
      "Low sugar, but frying and seasoning push saturated fat and sodium high — a meaningful share of a day's limit per pack.",
    ingredients: [
      { name: "Fresh Potatoes", flag: null, reason: "" },
      { name: "Vegetable Oil", flag: "caution", reason: "Frying oil — main driver of this product's high saturated fat." },
      { name: "Salt", flag: "caution", reason: "Contributes to this product's high sodium, on top of the vinegar seasoning below." },
      { name: "Vinegar Seasoning (maltodextrin, salt, vinegar flavor, sugar, flavor enhancers E621/E508/E627, acidity regulator E330, vegetable oils, anti-caking agent E551)", flag: "caution", reason: "Contains additional salt and flavor-enhancing additives (MSG-family compounds)." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://world.openfoodfacts.org/product/6281036115300"],
    dataNotes:
      "Open Food Facts lists this barcode's pack size as 48g, but every UAE/KSA retailer checked shows 45g — likely a regional labeling variance, not confirmed as the identical physical product OFF photographed. Allergens (estimate): none apparent.",
  },
  {
    id: "quest-chili-lime-protein-chips-32g",
    barcode: "888849006656",
    name: "Chili Lime Protein Chips",
    brand: "Quest",
    category: "snacks",
    servingLabel: "32g (1 pack)",
    servingSizeG: 32,
    isCaloMarket: true,
    priceAED: 23.9,
    image: "assets/catalogue/quest-chili-lime-chips-32g.jpg",
    nutrition: { calories: 140, sugar_g: 0.9, satFat_g: 1, sodium_mg: 320, fiber_g: 1, protein_g: 20 },
    allergens: ["dairy", "soy"],
    mayContainAllergens: [],
    concernMarkers: ["Sodium is high per 100g (over 1000mg) despite the otherwise clean protein-chip profile"],
    positiveFlags: ["20g protein per pack — the highest protein-to-size ratio of any snack in this catalogue", "Under 1g sugar"],
    verdict:
      "20g protein per pack, independently confirmed. But sodium runs over 1000mg per 100g — high enough to cancel out that protein credit.",
    ingredients: [
      { name: "Protein Blend (milk protein isolate, whey protein isolate)", flag: null, reason: "Declared allergen source (milk); also the source of this product's headline 20g protein." },
      { name: "Vegetable Oil", flag: null, reason: "" },
      { name: "Calcium Caseinate", flag: null, reason: "Dairy-derived." },
      { name: "Corn Starch", flag: null, reason: "" },
      { name: "Natural Flavors", flag: null, reason: "" },
      { name: "Salt", flag: "caution", reason: "Main driver of this product's high sodium." },
      { name: "Psyllium Husk", flag: null, reason: "Fiber source." },
      { name: "Onion Powder", flag: null, reason: "" },
      { name: "Paprika", flag: null, reason: "" },
      { name: "Spice", flag: null, reason: "" },
      { name: "Chia Seed", flag: null, reason: "" },
      { name: "Vinegar", flag: null, reason: "" },
      { name: "Lime Juice", flag: null, reason: "" },
      { name: "Sugar", flag: null, reason: "Under 1g per pack — minor contributor." },
      { name: "Yeast", flag: null, reason: "" },
      { name: "Citric Acid", flag: null, reason: "" },
      { name: "Turmeric Oleoresin", flag: null, reason: "Natural colorant." },
      { name: "Paprika Extract", flag: null, reason: "Natural colorant." },
      { name: "Lecithin", flag: null, reason: "Emulsifier." },
      { name: "Calcium Carbonate", flag: null, reason: "" },
      { name: "Yeast Extract", flag: null, reason: "" },
      { name: "Acacia Gum", flag: null, reason: "" },
      { name: "Stevia", flag: null, reason: "Non-caloric sweetener." },
    ],
    dataConfidence: "high",
    sourceUrls: ["https://questnutrition.com", "https://world.openfoodfacts.org/product/888849006656"],
    dataNotes:
      "Highest-confidence item in the spreadsheet-brand batch — per-serving figures independently confirmed by both Quest's own site and Open Food Facts, and the two sources' per-100g figures reconcile closely when this pack's per-serving numbers are scaled up.",
  },
  {
    id: "fulfil-chocolate-brownie-protein-bar-55g",
    barcode: "5391532122441",
    name: "Chocolate Brownie Protein Bar",
    brand: "Fulfil",
    category: "snacks",
    servingLabel: "55g (1 bar)",
    servingSizeG: 55,
    isCaloMarket: true,
    priceAED: 19.27,
    image: "assets/catalogue/fulfil-protein-bar-chocolate-brownie.png",
    nutrition: { calories: 197, sugar_g: 1.5, satFat_g: 4.4, sodium_mg: 118, fiber_g: 3.7, protein_g: 19.9 },
    allergens: ["dairy", "soy"],
    mayContainAllergens: ["eggs", "wheat", "tree_nuts", "peanut", "sesame"],
    concernMarkers: ["Contains sugar alcohols (maltitol) and an artificial sweetener (sucralose)", "Classified 'ultra-processed' by Open Food Facts' NOVA grouping, despite the health-focused marketing", "Saturated fat is high per 100g (~8g), mostly from the chocolate coating"],
    positiveFlags: ["19.9g protein per bar", "Low sugar for a chocolate-coated bar (1.5g)", "3.7g fiber per bar"],
    verdict:
      "20g protein and low sugar — but that low sugar comes from sugar alcohols and sweetener, not naturally. Saturated fat is also high.",
    ingredients: [
      { name: "Milk Protein", flag: null, reason: "Declared allergen source." },
      { name: "Milk Chocolate with Sweetener (maltitol, cocoa butter, whole milk powder, cocoa mass, soy lecithin, natural vanilla flavour)", flag: "caution", reason: "Contains maltitol, a sugar alcohol that can cause digestive discomfort in sensitive people at higher intakes." },
      { name: "Glycerol", flag: "caution", reason: "Humectant — generally recognized as safe." },
      { name: "Hydrolyzed Collagen", flag: "caution", reason: "Bovine-sourced — not suitable for vegetarians/vegans." },
      { name: "Soluble Corn Fibre", flag: null, reason: "" },
      { name: "Chocolate Drops", flag: null, reason: "" },
      { name: "Low Fat Cocoa", flag: null, reason: "" },
      { name: "Cocoa Butter", flag: null, reason: "" },
      { name: "Cocoa Mass", flag: null, reason: "" },
      { name: "Sweeteners (Maltitol, Sucralose)", flag: "caution", reason: "Sugar alcohol plus an artificial sweetener — the reason this bar shows only 1.5g sugar despite tasting sweet." },
      { name: "Artificial Flavors", flag: "caution", reason: "" },
      { name: "Soy Oil", flag: null, reason: "Declared allergen source." },
      { name: "Salt", flag: null, reason: "" },
      { name: "Milk Fat", flag: null, reason: "Declared allergen source." },
      { name: "Vitamins", flag: null, reason: "Fortification." },
      { name: "Soy Lecithin", flag: null, reason: "Declared allergen source." },
    ],
    dataConfidence: "high",
    sourceUrls: ["https://fulfilnutrition.com", "https://world.openfoodfacts.org/product/5391532122441"],
    dataNotes:
      "High confidence on nutrition/ingredients/allergens — corroborated across Open Food Facts and the brand's own site. Price (estimate): 19.27 AED, derived by dividing the only price found (a 6-pack at 115.64 AED) by 6, since no single-bar price was published anywhere — flagged as a calculated estimate, not a listed price. Sodium and satFat use the midpoint of each source's small range (116-120mg, 4.4-4.5g).",
  },
  {
    id: "halabi-mixed-nuts-28g",
    barcode: "5283005902028",
    name: "Mixed Nuts",
    brand: "Halabi",
    category: "snacks",
    servingLabel: "28g serving",
    servingSizeG: 28,
    isCaloMarket: true,
    priceAED: 20.85,
    image: "assets/catalogue/halabi-classic-mix.jpg",
    nutrition: { calories: 153, sugar_g: 1.6, satFat_g: 1.5, sodium_mg: 260, fiber_g: 2.3, protein_g: 5.7 },
    allergens: ["tree_nuts", "peanut"],
    mayContainAllergens: [],
    concernMarkers: ["Sodium is high per 100g (~930mg) — roasted/salted nuts add up fast, even though the base ingredient is naturally healthy"],
    positiveFlags: ["2.3g fiber per serving", "5.7g protein per serving from whole nuts, not a protein isolate"],
    verdict:
      "Real fiber and protein from whole nuts — but roasting and salting push sodium well past 'high' once normalized.",
    ingredients: [
      { name: "Peanuts", flag: "concern", reason: "Major allergen — can trigger severe, potentially life-threatening reactions in people with a peanut allergy." },
      { name: "Cashews", flag: "concern", reason: "Tree nut — major allergen." },
      { name: "Pistachios", flag: "concern", reason: "Tree nut — major allergen." },
      { name: "Almonds", flag: "concern", reason: "Tree nut — major allergen." },
      { name: "Hazelnuts", flag: "concern", reason: "Tree nut — major allergen." },
      { name: "Chickpeas", flag: null, reason: "" },
      { name: "Pumpkin Seeds", flag: null, reason: "" },
      { name: "Salt", flag: "caution", reason: "Main driver of this product's high sodium." },
    ],
    dataConfidence: "medium",
    sourceUrls: ["https://world.openfoodfacts.org/product/5283005902028", "https://noon.com"],
    dataNotes:
      "Open Food Facts' own record for this barcode is named 'Mix Noix Apéritif' with an empty brand field — the Halabi identity comes only from retailer pages whose URLs contain the barcode. Nutrition is well cross-validated between OFF and noon.com regardless. Two retailers give conflicting component lists (one adds corn) — used the components both agree on. Sodium and protein at the serving level are scaled directly from the found per-100g figures, not independent lookups. Price shown is the midpoint of a 17.40–24.30 AED range.",
  },
];

// Default demo persona — editable live in the Account tab. Values are a
// realistic subscriber profile, not placeholders; daily targets are
// computed from these via profile.js, not hardcoded.
const DEFAULT_PROFILE = {
  name: "Ahmed",
  gender: "male",
  age: 30,
  heightCm: 178, // 5'10" (177.8cm, rounded)
  weightKg: 72,
  targetWeightKg: 72, // same as current — goal is "eat healthy," not weight change
  goal: "eat_healthy",
  activityLevel: "very_active",
  allergies: ["dairy", "peanut"],
  // Simulated "how far into the day" — stands in for real meal-log data.
  consumedFraction: 0.55,
};
